---
- name: set timezone
  command: timedatectl set-timezone Europe/Oslo
  changed_when: false

- name: install ntp
  apt: pkg=ntp state=latest

- name: make sure ntp is running
  service: name=ntp state=running enabled=yes
