---
- name: install golang
  shell: curl -L https://storage.googleapis.com/golang/go{{ go.version }}.linux-amd64.tar.gz | tar -zxC /usr/local
         creates=/usr/local/go

- name: configure path
  copy: content="[ -d /usr/local/go/bin ] && export PATH=/usr/local/go/bin:$PATH\n"
        dest=/etc/profile.d/golang.sh
        owner=root
        group=root
        mode=0644
