---
- name: detect installed version
  command: head -1 {{ go.path_prefix }}/go/VERSION
  ignore_errors: yes
  register: go_version
  changed_when: go_version.stdout != 'go{}'.format(go.version)

- name: download tarball
  get_url: url=https://storage.googleapis.com/golang/go{{ go.version }}.linux-amd64.tar.gz
           dest=/var/tmp/go{{ go.version }}.linux-amd64.tar.gz
           checksum={{ go.checksum }}

- name: create path prefix
  file: path={{ go.path_prefix }}
        state=directory

- name: remove existing version
  file: path={{ go.path_prefix }}/go
        state=absent
  when: go_version.changed

- name: extract tarball
  unarchive: src=/var/tmp/go{{ go.version }}.linux-amd64.tar.gz
             dest={{ go.path_prefix }}
             creates={{ go.path_prefix }}/go
             copy=no
