---
- hosts: all
  become: yes
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
  roles:
    - ntp
    - golang
  tasks:
    - name: install packages
      apt: pkg={{ item }} state=latest
      with_items:
        - git
        - make
    - name: hide login message
      copy: dest=/home/vagrant/.hushlogin
            content=
            owner=vagrant
            group=vagrant
            mode=0644
    - name: create bash_profile
      copy: content="export GOPATH=/go\nexport PATH=${GOPATH}/bin:/usr/local/go/bin:$PATH\ncd ${GOPATH}/src/github.com/martinp/gounpack\n"
            dest=/home/vagrant/.bash_profile
            owner=vagrant
            group=vagrant
            mode=0644
    - name: set workspace permissions
      file: path=/go
            owner=vagrant
            group=vagrant
            recurse=yes
